name: flutter_starter
description: A new Flutter framework application.
# ğŸ”¥ğŸ‘åŸºäºfish_reduxçš„çº¯flutterå¿«é€Ÿå¼€å‘æ¡†æ¶ã€‚æ¡†æ¶é›†æˆé»‘å¤œæ¨¡å¼ã€å¤šè‰²å½©ä¸»é¢˜ã€å›½é™…åŒ–ã€åˆ‡æ¢å­—ä½“ã€ä¼˜ç¾åŠ¨ç”»ï¼Œ
# ä»¥åŠå„ç§å¸¸è§çš„ã€ä¸°å¯Œçš„å¼€å‘ç¤ºä¾‹ã€‚å¯ä»¥è®©ä½ å¿«é€Ÿçš„ä¸Šæ‰‹å¼€å‘ä¸€ä¸ªç§»åŠ¨åº”ç”¨APP(Android\iOS)ã€‚
# https://github.com/smarthane/flutter_starter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+100

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # flutter SDK >= 1.17.3-stable
  flutter:
    sdk: flutter
  # flutter intl å›½é™…åŒ–æ”¯æŒ
  flutter_localizations:
    sdk: flutter
  # åŒæ—¶æ”¯æŒandroidå’Œios
  # æ”¯æŒäº‹åŠ¡å’Œæ‰¹é‡æ“ä½œ
  # æ”¯æŒæ’å…¥/æŸ¥è¯¢/æ›´æ–°/åˆ é™¤æ“ä½œ
  # åœ¨iOSå’ŒAndroidä¸Šçš„åå°çº¿ç¨‹ä¸­æ‰§è¡Œæ•°æ®åº“æ“ä½œ
  # https://github.com/tekartik/sqflite
  sqflite: ^1.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # é—²é±¼reduxçŠ¶æ€ç®¡ç†
  # https://github.com/alibaba/fish-redux
  fish_redux: ^0.3.4
  # æœ¬åœ°key-valueå­˜å‚¨
  # https://github.com/flutter/plugins/tree/master/packages/shared_preferences
  shared_preferences: ^0.5.2+2
  # æœ¬åœ°å¯¹è±¡å­˜å‚¨
  # https://github.com/lesnitsky/flutter_localstorage
  localstorage: ^2.0.0
  # ä¸€ä¸ªçœŸæ­£æ„ä¹‰ä¸Šçš„flutter Toaståº“!
  # https://github.com/MMMzq/bot_toast/blob/master/README_zh.md
  bot_toast: ^3.0.5
  # ä¸€ä¸ªæä¾›ä¸Šæ‹‰åŠ è½½å’Œä¸‹æ‹‰åˆ·æ–°çš„ç»„ä»¶,åŒæ—¶æ”¯æŒAndroidå’ŒIos
  # https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^1.6.3
  # flutteræœ€å¼ºå¤§çš„siwiper, å¤šç§å¸ƒå±€æ–¹å¼ï¼Œæ— é™è½®æ’­ï¼ŒAndroidå’ŒIOSåŒç«¯é€‚é….
  # https://github.com/best-flutter/flutter_swiper/blob/master/README-ZH.md
  flutter_swiper: ^1.1.6
  # A flutter library to show images from the internet and keep them in the cache directory.
  # https://github.com/Baseflow/flutter_cached_network_image
  cached_network_image: ^2.2.0
  # A Flutter plugin that provides a WebView widget on Android and iOS.
  # https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^0.3.24
  # Plugin that allows Flutter to communicate with a native WebView.
  # https://github.com/fluttercommunity/flutter_webview_plugin
  flutter_webview_plugin: ^0.3.11
  # å¯åŠ¨ç¬¬ä¸‰æ–¹app
  # https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^5.1.6
  # A flutter plugin for install apk for android; and using url to go to app store for iOS.
  # https://github.com/hui-z/flutter_install_plugin
  install_plugin: ^2.0.1
  # This Flutter plugin provides an API for querying information about an application package.
  # https://github.com/flutter/plugins/tree/master/packages/package_info
  package_info: ^0.4.3+2
  # ç½‘ç»œè¯·æ±‚åº“
  # https://github.com/flutterchina/dio
  dio: ^3.0.10
  # A cookie manager for Dio.
  # https://github.com/flutterchina/dio/tree/master/plugins/cookie_manager
  dio_cookie_manager: ^1.0.0
  # A cookie manager for http requests in Dart, by which you can deal with the complex cookie policy and persist cookies easily.
  # https://github.com/flutterchina/cookie_jar
  cookie_jar: ^1.0.1
  # Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  # https://github.com/flutter/plugins/tree/master/packages/connectivity
  connectivity: ^2.0.2
  # This plugin provides a cross-platform (iOS, Android) API to request permissions and check their status. You can also open the device's app settings so users can grant a permission.
  # On Android, you can show a rationale for requesting a permission.
  # https://github.com/baseflowit/flutter-permission-handler
  permission_handler: ^5.0.1+1
  # A Dart library for unescaping HTML-encoded strings. Html Encoder/Decoder
  # https://github.com/filiph/html_unescape
  html_unescape: ^1.0.2
  # A Flutter widget for rendering html and css as Flutter widgets.
  # https://github.com/Sub6Resources/flutter_html
  flutter_html: ^0.10.4
  # è°ç”¨è°é—ªäº® A package provides an easy way to add shimmer effect in Flutter project
  # https://github.com/hnvn/flutter_shimmer
  shimmer: ^1.1.2
  # lottieåŠ¨ç”»
  # https://github.com/xvrh/lottie-flutter
  lottie: ^0.7.0+1
  # A cross platform plugin for displaying local notifications.
  # https://github.com/MaikuB/flutter_local_notifications
  flutter_local_notifications: ^3.0.1+6
  ################################################################################################
  ################################################################################################
  # Demoç¤ºä¾‹
  # ç€‘å¸ƒæµ A Flutter staggered grid view which supports multiple columns with rows of varying sizes.
  # https://github.com/letsar/flutter_staggered_grid_view
  flutter_staggered_grid_view: ^0.3.2
  # åŸå¸‚é€‰æ‹©å™¨
  # https://github.com/hanxu317317/city_pickers
  city_pickers: ^0.2.0
  # Highly customizable, feature-packed Flutter Calendar with gestures, animations and multiple formats.
  # https://github.com/aleksanderwozniak/table_calendar
  # table_calendar: ^2.3.1
  # æ”¯æŒæœ¬åœ°å›¾ç‰‡å¤šé€‰ï¼Œæœ¬åœ°è§†é¢‘å¤šé€‰ï¼Œæ”¯æŒå°†ç½‘ç»œå›¾ç‰‡ä¿å­˜åˆ°ç›¸å†Œï¼Œæ”¯æŒæˆªå›¾ä¿å­˜åˆ°ç›¸å†Œï¼Œ
  # æ”¯æŒå°†ç½‘ç»œè§†é¢‘ä¿å­˜åˆ°ç›¸å†Œï¼Œæ”¯æŒé¢„è§ˆè§†é¢‘å’Œé¢„è§ˆå›¾ç‰‡åŠŸèƒ½ï¼Œæ”¯æŒä¸»é¢˜é¢œè‰²è®¾ç½®
  # https://github.com/lisen87/image_pickers
  # iOS : platform :ios, '10.0'
  # Android: minSdkVersion 19 targetSdkVersion 29 compileSdkVersion 29
  # 1.0.8 flutter sdk >= 1.20.0 å¯ä»¥æ ¹æ®è‡ªå·±çš„å·¥ç¨‹éœ€æ±‚é€‰æ‹©æœ€æ–°ç‰ˆæœ¬
  image_pickers: ^1.0.7
  # å±å¹•é€‚é…
  # A flutter plugin for adapting screen and font size.Let your UI display a reasonable layout on different screen sizes!
  # https://github.com/OpenFlutter/flutter_screenutil/
  flutter_screenutil: ^3.2.0
  ################################################################################################
  ################################################################################################
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: happy # ç«™é…· å¿«ä¹å­—ä½“  https://fonts.google.com/?selection.family=Noto+Sans+SC&subset=chinese-simplified
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf
    - family: butter # ç«™é…· é»„æ²¹å­—ä½“ https://www.zcool.com.cn/special/zcoolfonts/
      fonts:
        - asset: assets/fonts/ZCOOLButter-Regular.ttf
  assets:
    - assets/images/
    - assets/animations/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
